# Lab 01 - Bài tập

## PYTHON

1. In toàn bộ các số chẵn từ 1000 đến 2000

In [1]:
for i in range(1000, 2001):
    if (i % 2 == 0):
        print(i)

1000
1002
1004
1006
1008
1010
1012
1014
1016
1018
1020
1022
1024
1026
1028
1030
1032
1034
1036
1038
1040
1042
1044
1046
1048
1050
1052
1054
1056
1058
1060
1062
1064
1066
1068
1070
1072
1074
1076
1078
1080
1082
1084
1086
1088
1090
1092
1094
1096
1098
1100
1102
1104
1106
1108
1110
1112
1114
1116
1118
1120
1122
1124
1126
1128
1130
1132
1134
1136
1138
1140
1142
1144
1146
1148
1150
1152
1154
1156
1158
1160
1162
1164
1166
1168
1170
1172
1174
1176
1178
1180
1182
1184
1186
1188
1190
1192
1194
1196
1198
1200
1202
1204
1206
1208
1210
1212
1214
1216
1218
1220
1222
1224
1226
1228
1230
1232
1234
1236
1238
1240
1242
1244
1246
1248
1250
1252
1254
1256
1258
1260
1262
1264
1266
1268
1270
1272
1274
1276
1278
1280
1282
1284
1286
1288
1290
1292
1294
1296
1298
1300
1302
1304
1306
1308
1310
1312
1314
1316
1318
1320
1322
1324
1326
1328
1330
1332
1334
1336
1338
1340
1342
1344
1346
1348
1350
1352
1354
1356
1358
1360
1362
1364
1366
1368
1370
1372
1374
1376
1378
1380
1382
1384
1386
1388
1390
1392
1394
1396
1398


2. Viết chương trình tìm tất cả các số chia hết cho 7 nhưng không phải bội số của 5, nằm trong đoạn 2000 và 3200 (tính cả 2000 và 3200). Các số thu được sẽ được in thành chuỗi trên một dòng, cách nhau bằng dấu phẩy

In [2]:
# Tạo mảng result để lưu trữ kết quả
result = []

# Duyệt các số từ 2000 đến 3200
for num in range(2000, 3201):
    if num % 7 == 0 and num % 5 != 0:
        result.append(str(num))

print(', '.join(result))

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199


3. Với số nguyên n nhất định, hãy viết chương trình hiển thị dictionary chứa các cặp (i, i*i) ; biết i có giá trị từ 1..n


In [3]:
# Tạo hàm hiển thị dictionary
def create_dict(n):
    # Trả về kết quả là một dictionary, key là số từ 1 đến n, value là bình phương của key
    return {i: i*i for i in range(1, n+1)}

n = 5
print(create_dict(n))

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


4. Viết chương trình chấp nhận một chuỗi số, phân tách bằng dấu phẩy từ giao diện điều khiển, tạo ra một List  và một tuple chứa mọi số.

    Ví dụ:

    ```
    Đầu vào được cung cấp là 34,67,55,33,12,98 thì đầu ra là:

    ['34', '67', '55', '33', '12', '98']
    ('34', '67', '55', '33', '12', '98')

    ```


In [4]:
numbers = input("Nhập dãy số cách nhau bởi dấu phẩy: ")
numbers_list = numbers.split(",")
numbers_tuple = tuple(numbers_list)

print(numbers_list)
print(numbers_tuple)

['32', '6', '7', '14', '2', '10', '9']
('32', '6', '7', '14', '2', '10', '9')


5. Viết chương trình hỏi người dùng một số tự nhiên n và in ra tất cả ước số của con số đó.

In [5]:
# Hỏi người dùng nhập số tự nhiên
n = int(input("Nhập một số tự nhiên n: "))

# Kiểm tra và in ra tất cả các ước số của số n
print(f"Các ước số của {n} là:")
for i in range(1, n + 1):
    if n % i == 0:
        print(i)


Các ước số của 20 là:
1
2
4
5
10
20


6. Viết chương trình Python tính tổng các phần tử của một danh sách.

In [6]:
def sum_list(elements):
    return sum(elements)

numbers = [1, 2, 3, 4, 5]
print(sum_list(numbers))

15


7. Nhập vào một list L có các phần tử bao gồm chuỗi và số nguyên, hãy tìm và in ra chuỗi có độ dài lớn nhất và số nguyên có giá trị nhỏ nhất

In [7]:
# Tạo hàm tìm chuỗi có độ dài lớn nhất và số nguyên có giá trị nhỏ nhất
def find_longest_string_and_smallest_number(numbers):
    # Kiểm tra xem phần tử trong list có phải là string hay không
    strings = [x for x in L if isinstance(x, str)]

    # Kiểm tra xem phần tử trong list có phải là số nguyên hay không
    numbers = [x for x in L if isinstance(x, int)]

    # Tìm chuỗi có độ dài lớn nhất
    longest_string = max(strings, key=len) if strings else None

    # Tìm số nguyên có giá trị nhỏ nhất
    smallest_number = min(numbers) if numbers else None

    return longest_string, smallest_number

# Tạo list L
L = [1, "Hello", 2, "World", 3, "Python", 4]

# Gọi hàm find_longest_string_and_smallest_number
longest_string, smallest_number = find_longest_string_and_smallest_number(L)

# In kết quả
print("Longest string:", longest_string)
print("Smallest number:", smallest_number)

Longest string: Python
Smallest number: 1


8. Nhập vào một list L có các phần tử bao gồm chuỗi và số nguyên, hãy tìm và in ra chuỗi có độ dài lớn nhất và số nguyên có giá trị nhỏ nhất

In [8]:
# Tạo hàm tìm chuỗi có độ dài lớn nhất và số nguyên có giá trị nhỏ nhất
def find_longest_string_and_smallest_number(numbers):
    # Kiểm tra xem phần tử trong list có phải là string hay không
    strings = [x for x in L if isinstance(x, str)]

    # Kiểm tra xem phần tử trong list có phải là số nguyên hay không
    numbers = [x for x in L if isinstance(x, int)]

    # Tìm chuỗi có độ dài lớn nhất
    longest_string = max(strings, key=len) if strings else None

    # Tìm số nguyên có giá trị nhỏ nhất
    smallest_number = min(numbers) if numbers else None

    return longest_string, smallest_number

# Tạo list L
L = [1, "Hello", 2, "World", 3, "Python", 4]

# Gọi hàm find_longest_string_and_smallest_number
longest_string, smallest_number = find_longest_string_and_smallest_number(L)

# In kết quả
print("Longest string:", longest_string)
print("Smallest number:", smallest_number)

Longest string: Python
Smallest number: 1


9. Viết hàm đưa vào 1 list số nguyên L và 1 số nguyên dương a. Hãy tính và trả về giá trị trung bình của a phần tử đầu tiên trong L

In [9]:
# Viết hàm tính trung bình cộng của a phần tử đầu tiên trong một list
def average_of_first_a_elements(L, a):
    # Trả về None nếu a lớn hơn độ dài của danh sách
    if a <= len(L):
        return sum(L[:a]) / a
    # Ngược lại trả về trung bình cộng của a phần tử đầu tiên
    else:
        return None

L = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = 3
result = average_of_first_a_elements(L, a)

if result is not None:
    print(f"Giá trị trung bình của phần tử {a} đầu tiên trong danh sách là: {result}")
else:
    print(f"Số phần tử {a} trong danh sách không đủ để tính trung bình.")

Giá trị trung bình của phần tử 3 đầu tiên trong danh sách là: 2.0


10. Viết hàm nhận vào một danh sách các số nguyên. Hãy viết hàm trả về một danh sách gồm các số không trùng nhau trong danh sách ban đầu

In [10]:
def unique_elements(L):
    return list(set(L))

L = [1, 2, 2, 3, 4, 4, 5, 5]
print(unique_elements(L))

[1, 2, 3, 4, 5]


11. Viết hàm có tham số đầu vào là một list L có các phần tử là chuỗi. Hãy tạo ra một dictionary D mã hóa, với mỗi một phần tử trong L được mã hóa thành một con số (theo thứ tự từ 0 tăng dần lên 1 đơn vị). Sau đó trả về list đã được mã hóa

    Ví dụ:

    ```
    Cho L = ["đen","vàng","xanh","vàng","xanh","đỏ","hồng"]

    Xây dựng dictionary mã hóa:
    D = {'đen':0,'vàng':1,'xanh':2,'đỏ':3,'hồng':4}

    Trả về List mã hóa:
    L_mahoa = [0, 1, 2, 1, 2, 3, 4]
    ```

In [11]:
def encode_list(L):
    D = {v: k for k, v in enumerate(sorted(set(L)))}
    L_encoded = [D[i] for i in L]
    return L_encoded

L = ["đen", "vàng", "xanh", "vàng", "xanh", "đỏ", "hồng"]
print(encode_list(L))

[3, 1, 2, 1, 2, 4, 0]


12. Viết hàm kết hợp hai dictionary dựa vào key như sau:

    ```python
    d1 = {'a': 100, 'b': 200, 'c':300}
    d2 = {'a': 300, 'b': 200, 'd':400}
    Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})
    ```

In [12]:
from collections import Counter

def combine_dicts(d1, d2):
    return dict(Counter(d1) + Counter(d2))

d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
print(combine_dicts(d1, d2))

{'a': 400, 'b': 400, 'c': 300, 'd': 400}


## NUMPY

Sử dụng mảng numpy cho các bài tập dưới đây

13. Tạo một vector 0 có 10 phần tử, trong đó phần tử thứ 5 có giá trị là 1

In [13]:
import numpy as np

vector = np.zeros(10)
vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


14. Tạo một ma trận kích thước 5x5, mỗi phần tử là các số thực có giá trị từ 1..5

In [14]:
import numpy as np

matrix = np.array([[i for i in range(1, 6)] for _ in range(5)])

print(matrix)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


15. Phát sinh ngẫu nhiên một mảng ndarray có kích thước là n nhập từ phím, mỗi phần tử là các số nguyên có giá trị từ 1..100. Bạn hãy thực hiện:
- Tính tổng mảng
- Tìm phần tử lớn nhất
- Tìm giá trị trung bình, trung vị, phân vị 50 và phân vị 75
- Tìm miền giá trị, miền phân vị
- Tính phương sai và độ lệch chuẩn
- Có bao nhiêu phần tử có một chữ số?
- In ra các phần tử có giá trị từ 80..100. Tính tổng các phần tử này.
- In ra m giá trị lớn nhất trong mảng. Biết rằng m = n//4
- Bạn hãy tạo ra một mảng từ mảng ban đầu; biết rằng mỗi phần tử của mảng mới bằng một phần tử của mảng ban đầu chia lấy dư cho 20.
- Sắp xếp mảng giảm dần.

In [15]:
import numpy as np

# Phát sinh mảng ngẫu nhiên
n = int(input("Nhập kích thước mảng n: "))
arr = np.random.randint(1, 101, size=n)

# Tính tổng mảng
tong_mang = np.sum(arr)

# Tìm phần tử lớn nhất
max_element = np.max(arr)

# Tìm giá trị trung bình, trung vị, phân vị 50 và phân vị 75
trung_binh = np.mean(arr)
trung_vi = np.median(arr)
phan_vi_50 = np.percentile(arr, 50)
phan_vi_75 = np.percentile(arr, 75)

# Tìm miền giá trị, miền phân vị
mien_gia_tri = np.ptp(arr)
mien_phan_vi = np.percentile(arr, 75) - np.percentile(arr, 25)

# Tính phương sai và độ lệch chuẩn
phuong_sai = np.var(arr)
do_lech_chuan = np.std(arr)

# Số lượng phần tử có một chữ số
so_luong_mot_chu_so = np.sum((arr >= 1) & (arr <= 9))

# In ra các phần tử có giá trị từ 80 đến 100 và tính tổng
phane_tu_80_100 = arr[(arr >= 80) & (arr <= 100)]
tong_phan_tu_80_100 = np.sum(phane_tu_80_100)

# In ra m giá trị lớn nhất trong mảng (m = n//4)
m = n // 4
m_gia_tri_lon_nhat = np.sort(arr)[-m:]

# Tạo một mảng mới từ mảng ban đầu
mang_moi = arr % 20

# Sắp xếp mảng giảm dần
mang_giam_dan = np.sort(arr)[::-1]

# In kết quả
print("Mảng ngẫu nhiên:", arr)
print("Tổng mảng:", tong_mang)
print("Phần tử lớn nhất:", max_element)
print("Giá trị trung bình:", trung_binh)
print("Trung vị:", trung_vi)
print("Phân vị 50:", phan_vi_50)
print("Phân vị 75:", phan_vi_75)
print("Miền giá trị:", mien_gia_tri)
print("Miền phân vị:", mien_phan_vi)
print("Phương sai:", phuong_sai)
print("Độ lệch chuẩn:", do_lech_chuan)
print("Số lượng phần tử có một chữ số:", so_luong_mot_chu_so)
print("Phần tử từ 80 đến 100:", phane_tu_80_100)
print("Tổng các phần tử từ 80 đến 100:", tong_phan_tu_80_100)
print(f"{m} giá trị lớn nhất trong mảng:", m_gia_tri_lon_nhat)
print("Mảng mới từ mảng ban đầu (mỗi phần tử chia lấy dư cho 20):", mang_moi)
print("Mảng giảm dần:", mang_giam_dan)

Mảng ngẫu nhiên: [59 76 38 67  8]
Tổng mảng: 248
Phần tử lớn nhất: 76
Giá trị trung bình: 49.6
Trung vị: 59.0
Phân vị 50: 59.0
Phân vị 75: 67.0
Miền giá trị: 68
Miền phân vị: 29.0
Phương sai: 590.64
Độ lệch chuẩn: 24.303086223770016
Số lượng phần tử có một chữ số: 1
Phần tử từ 80 đến 100: []
Tổng các phần tử từ 80 đến 100: 0
1 giá trị lớn nhất trong mảng: [76]
Mảng mới từ mảng ban đầu (mỗi phần tử chia lấy dư cho 20): [19 16 18  7  8]
Mảng giảm dần: [76 67 59 38  8]


16. Phát sinh ngẫu nhiên mảng các số nguyên có 10 phần tử có giá trị từ 1..100. Bạn hãy viết chương trình chọn ngẫu nhiên n mẫu (có hoàn lại), mỗi mẫu gồm 4 phần tử từ mảng ban đầu (với n nhập từ bàn phím). Thực hiện:

- Hiển thị các mẫu trên
- Tính tổng các mẫu trên
- Hiển thị mảng gồm n phần tử, mỗi phần tử chứa giá trị trung bình của các mẫu trên


In [16]:
# Phát sinh mảng ngẫu nhiên có 10 phần tử
mang_ngau_nhien = np.random.randint(1, 101, size=10)

# Nhập số lượng mẫu n
n = int(input("Nhập số lượng mẫu n: "))

# Phát sinh mẫu ngẫu nhiên
mau_ngau_nhien = np.random.choice(mang_ngau_nhien, size=(n, 4), replace=True)

# Hiển thị các mẫu
print("Các mẫu:")
print(mau_ngau_nhien)

# Tính tổng các mẫu
tong_mau = np.sum(mau_ngau_nhien, axis=1)
print("\nTổng mẫu:")
print(tong_mau)

# Hiển thị mảng gồm n phần tử, mỗi phần tử chứa giá trị trung bình của các mẫu
trung_binh_mau = np.mean(mau_ngau_nhien, axis=1)
print("\nMảng gồm n phần tử, mỗi phần tử chứa giá trị trung bình của các mẫu:")
print(trung_binh_mau)

Các mẫu:
[[56 56 57 89]
 [89 53 56 82]
 [13 13 89 56]
 [57 13  1 84]
 [13 82 57 89]]

Tổng mẫu:
[258 280 171 155 241]

Mảng gồm n phần tử, mỗi phần tử chứa giá trị trung bình của các mẫu:
[64.5  70.   42.75 38.75 60.25]


17. Phát sinh ngẫu nhiên mảng các số nguyên có 10 phần tử có giá trị từ 1..100. Bạn hãy viết chương trình hiển thị 10 hoán vị không giống nhau và không giống với mỗi ban đầu.

In [17]:
# Phát sinh mảng ngẫu nhiên có 10 phần tử
mang_ngau_nhien = np.random.randint(1, 101, size=10)

# Hiển thị mảng ban đầu
print("Mảng ban đầu:", mang_ngau_nhien)

# Phát sinh và hiển thị 10 hoán vị không giống nhau và không giống với mảng ban đầu
print("\n10 hoán vị không giống nhau:")
for _ in range(10):
    hoan_vi = np.random.permutation(mang_ngau_nhien)
    print(hoan_vi)

Mảng ban đầu: [38 40 78 90 57 59 31 61 98 52]

10 hoán vị không giống nhau:
[59 98 52 78 38 57 61 40 90 31]
[57 59 98 78 38 31 61 40 52 90]
[38 78 61 40 59 98 90 31 57 52]
[40 78 90 59 52 38 98 31 57 61]
[78 52 61 57 31 90 40 38 59 98]
[40 59 98 31 38 78 57 61 90 52]
[78 40 59 31 38 57 61 52 90 98]
[90 59 78 98 52 40 57 38 61 31]
[57 52 38 98 40 59 90 31 78 61]
[61 59 57 40 31 52 38 90 98 78]
